/*
 * generated by Xtext 2.16.0
 */
package org.example.entities.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.entities.ui.internal.EntitiesActivator;

public class EntitiesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntitiesActivator.getInstance().getInjector("org.example.entities.Entities");
	}

}
