/**
 * generated by Xtext 2.16.0
 */
package org.example.entities;

import org.example.entities.AbstractEntitiesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
