/**
 * generated by Xtext 2.16.0
 */
package org.example.entities.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.entities.EntitiesRuntimeModule;
import org.example.entities.EntitiesStandaloneSetup;
import org.example.entities.ide.EntitiesIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EntitiesIdeSetup extends EntitiesStandaloneSetup {
  @Override
  public Injector createInjector() {
    EntitiesRuntimeModule _entitiesRuntimeModule = new EntitiesRuntimeModule();
    EntitiesIdeModule _entitiesIdeModule = new EntitiesIdeModule();
    return Guice.createInjector(Modules2.mixin(_entitiesRuntimeModule, _entitiesIdeModule));
  }
}
