/**
 * generated by Xtext 2.16.0
 */
package org.example.entities.ide;

import org.example.entities.ide.AbstractEntitiesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EntitiesIdeModule extends AbstractEntitiesIdeModule {
}
