/*
 * generated by Xtext 2.17.0
 */
package org.example.entities.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntitiesScopeProvider extends DelegatingScopeProvider {
}
