/**
 * generated by Xtext 2.16.0
 */
package org.example.entities.validation;

import org.example.entities.validation.AbstractEntitiesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EntitiesValidator extends AbstractEntitiesValidator {
}
